### ISSUE TITLE
Gazetteer review

### ISSUE THREAD

**Issue by itcareerswitch** [Lutanda-Muchenje/lutandaMuchenje#1]
- [x] Float select over top centre of map
- [x] Leaflet Extra Markers with font awesome
- [x] Remove location marker
- [x] Style polygon with L.geoJSON options
- [x] Format all dates and numbers
- [x] Include picture in news modal

**Comment by Lutanda-Muchenje** [comment]
I will now remove the tourism modal as I believe it's data is better returned by clicking the markers. Same with the wiki modal. While doing so, I will also try and reduce the amount of information overall returned and see if the profile modal's design can be improved
